name: GHCR-DigitalOcean

on:
  # Trigger the workflow on push
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push to GHCR -> DigitlOcean
    runs-on: ubuntu-latest

    steps:
      # Checkout the Repository
      - name: Checking out the repository
        uses: actions/checkout@v2

      # Setting up Docker Builder
      - name: Set up Docker Builder
        uses: docker/setup-buildx-action@v1

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: hub.docker.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push to Github Container Registry
      - name: Push to Github Container Registry
        uses: docker/build-push-action@v2
        with:
          version: latest
          push: true
          tags: farahblog/${{ github.repository }}:latest
