name: deployando github actions
on: push 
jobs:
  deploy: 
    name: deployando
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build and push
      uses: docker/build-push-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ github.repository }}
        tag_with_ref: true
        tag_with_sha: true 
        tags: ${{ github.sha }}
     
   production:
      name: deploy app on docker
             
      steps:
      - name: deployment on server docker 
      - uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.HOST }}    
          USERNAME: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.KEY }} 
          PORT: ${{ secrets.PORT  }}
          script: | 
            docker rm -fv ${{ github.repository_owner }}
            docker run -dit -p 80:80 --restart always ---name cont_web $(echo $${{ github.repository }}   

