name: deployando github actions
on: push 
jobs:
  deploy: 
    name: Build Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build and push
      uses: docker/build-push-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ github.repository }}
        tag_with_ref: true
        tag_with_sha: true 
        tags: ${{ github.sha }}
     
  production:
    name: deploy app on docker
    runs-on: ubuntu-latest
    
    steps:
    - name: Deployment on server docker 
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}    
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }} 
        port: ${{ secrets.PORT  }}
        passphrase: ${{ secrets.PASS }}
        script: | 
            docker rm -fv ${{ github.repository_owner }}
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker run -dit -p 80:80 --restart always --name cont_web $${{ github.repository }}   

